[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  command! Tig :TigOpenProjectRootDir<cr>
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  source ~/.config/nvim/plugins/winresizer.vim
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'pgr0ss/vim-github-url'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  source ~/.config/nvim/plugins/vim-tmux-navigator.vim
'''

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
depends = ['tpope/vim-dadbod']
hook_add = '''
  source ~/.config/nvim/plugins/vim-dadbod-ui.vim
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
  nnoremap <C-n> :NvimTreeToggle<CR>
  source ~/.config/nvim/plugins/nvim-tree.vim
  lua require('plugins/nvim-tree')
'''

[[plugins]]
repo = 'projekt0n/github-nvim-theme'
hook_add = '''
  autocmd ColorScheme * hi StatusLine   gui=NONE guifg=white guibg=NONE 
  autocmd ColorScheme * hi StatusLineNC gui=NONE guifg=grey  guibg=NONE 

  autocmd ColorScheme * hi Search ctermfg=0 ctermbg=211 guibg=#6b6b4f
  let g:github_dark_sidebar = 0
  colorscheme github_dark
'''

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
depends = ['rbgrouleff/bclose.vim']
hook_add = '''
  nmap <leader>gg :TigOpenProjectRootDir<CR>
'''

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'sindrets/diffview.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  lua require('plugins/diffview')
'''

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  nnoremap <silent><C-p> <cmd>lua require('telescope.builtin').find_files()<cr>
  nnoremap <silent><S-f> <cmd>lua require('telescope.builtin').live_grep()<cr>
  nnoremap <silent><S-p> <cmd>lua require('telescope.builtin').buffers()<cr>
  lua require('plugins/telescope')

  nmap <silent><leader>ii  :e ~/.ignore<CR>
'''

[[plugins]]
repo = 'pwntester/octo.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  lua require('plugins/octo')
'''

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = '~/work/hello-beautiful-world-vim'

