[[plugins]]
repo = 'ulwlu/elly.vim'
hook_add = '''
  hi! Normal ctermbg=NONE guibg=NONE
  hi! NonText ctermbg=NONE guibg=NONE
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo =  'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fzf.vim
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  source ~/.config/nvim/plugins/winresizer.vim
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'pgr0ss/vim-github-url'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  source ~/.config/nvim/plugins/vim-tmux-navigator.vim
'''

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
depends = ['tpope/vim-dadbod']
hook_add = '''
  source ~/.config/nvim/plugins/vim-dadbod-ui.vim
'''

[[plugins]]
repo = 'APZelos/blamer.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/blamer.vim
'''

# [[plugins]]
# repo = 'fxn/vim-monochrome'
# hook_add = '''
#   source ~/.config/nvim/plugins/monochrome.vim
# '''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
  nnoremap <C-n> :NvimTreeToggle<CR>
  source ~/.config/nvim/plugins/nvim-tree.vim
  lua require('plugins/nvim-tree')
'''

[[plugins]]
repo = 'projekt0n/github-nvim-theme'
hook_add = '''
  autocmd ColorScheme * hi StatusLine   gui=NONE guifg=white guibg=NONE 
  autocmd ColorScheme * hi StatusLineNC gui=NONE guifg=grey  guibg=NONE 
  autocmd ColorScheme * hi DiffAdd      gui=none guifg=NONE  guibg=#12261E
  autocmd ColorScheme * hi DiffDelete   gui=NONE guifg=NONE  guibg=#301A1F
  autocmd ColorScheme * hi DiffChange   gui=none guifg=NONE  guibg=#3B4261
  let g:github_dark_sidebar = 0
  colorscheme github_dark
'''

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
depends = ['rbgrouleff/bclose.vim']
hook_add = '''
  nmap <leader>gg :TigOpenProjectRootDir<CR>
'''

[[plugins]]
repo = 'skanehira/translate.vim'
hook_add = '''
  vnoremap <C-t> :Translate<CR>
'''

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  lua require('plugins/gitsigns')
  nmap ! :Gitsigns preview_hunk<CR>
'''

[[plugins]]
repo = 'sindrets/diffview.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  lua require('plugins/diffview')
'''
