[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  source ~/.config/nvim/plugins/winresizer.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  command! Tig :TigOpenProjectRootDir<cr>
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''


[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  source ~/.config/nvim/plugins/vim-tmux-navigator.vim
'''

[[plugins]]
repo = 'pwntester/octo.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  lua require('plugins/octo')
'''

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  nnoremap <silent><C-p> <cmd>lua require('telescope.builtin').find_files()<cr>
  nnoremap <silent><S-f> <cmd>lua require('telescope.builtin').live_grep()<cr>
  nnoremap <silent><S-p> <cmd>lua require('telescope.builtin').buffers()<cr>
  lua require('plugins/telescope')

  nmap <silent><leader>ii  :e ~/.ignore<CR>
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'pgr0ss/vim-github-url'

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
depends = ['tpope/vim-dadbod']
hook_add = '''
  source ~/.config/nvim/plugins/vim-dadbod-ui.vim
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'xiyaowong/transparent.nvim'
hook_add = '''
  lua require('plugins/transparent')
'''

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
  nnoremap <C-n> :NvimTreeFindFile<CR>
  lua require('plugins/nvim-tree')
'''

[[plugins]]
repo = 'projekt0n/github-nvim-theme'
hook_add = '''
  autocmd ColorScheme * hi StatusLine   gui=NONE guifg=white guibg=NONE 
  autocmd ColorScheme * hi StatusLineNC gui=NONE guifg=grey  guibg=NONE 

  autocmd ColorScheme * hi SeNVIDIA GeForce RTXNVIDIA GeForce RTXarch ctermfg=0 ctermbg=211 guibg=#6b6b4f
  let g:github_dark_sidebar = 0
  colorscheme github_dark
'''

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
depends = ['rbgrouleff/bclose.vim']
hook_add = '''
  nmap <leader>gg :TigOpenProjectRootDir<CR>
'''

[[plugins]]
repo = 'nathom/filetype.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'sindrets/diffview.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  lua require('plugins/diffview')
'''

[[plugins]]
repo = 'preservim/vim-indent-guides'

[[plugins]]
repo = 'xiyaowong/transparent.nvim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
# repo = 'TakuroSugahara/graphql-client-vim'
repo = '~/work/graphql-client-vim'
hook_add = '''
let g:graphql_client_workspaces = get(g:, 'graphql_client_workspaces', {
      \ 'student': {
      \   'endpoint': 'http://localhost:8080/api/student/graphql',
      \   'headers': 
      \     {
      \       'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c.student',
      \     }
      \   ,
      \ },
      \ 'admin': {
      \   'endpoint': 'http://localhost:8080/api/admin/graphql',
      \   'headers': 
      \     {
      \       'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
      \     }
      \   ,
      \ },
      \})
'''
