name: Code Review

on:
  pull_request:
    # PRの作成時とDraftからreview可能になったとき
    # types: [opened, reopened, ready_for_review]
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

jobs:
  review-bot:
    name: Review PR by GPT
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions. Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc'
          # PROMPT: >
          #   As an experienced software engineer, conduct a concise code review for the following code patch, highlighting specific areas for improvement or potential bugs. 
          #   There's no need for explanations of the functionality, or introductory and concluding remarks. 
          #   If there are differences between the code before and after the changes, review the code after the changes
